[workspace]
members = [
	"core",
	"back",
	"tui",
]

[profile.dev]
opt-level = 1
lto = false
overflow-checks = true
debug = true
debug-assertions = true
incremental = true

[profile.dev.build-override]
opt-level = 2


[profile.release]
debug = true
lto = true
