[package]
name = "ironic-backend"
version = "0.1.0"
authors = ["meta <eigenform@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty-hex = "0.2.1"
ironic-core = { path = "../core" }
