import { Button, VerticalBox, TabWidget, AboutSlint, GridBox, GroupBox, Spinner } from "std-widgets.slint";
import { OptionsPane, LogOptionDesc } from "options-pane.slint";
import { ArmEmu, LogDesc } from "arm-emu.slint";

component WipView inherits GroupBox {
    title: "App under development, this pane isn't ready yet!";
    Spinner {indeterminate: true;}
}

export component AppWindow inherits Window {
    title: "ironic - Low Level Wii System Research Emulator";
    preferred-width: 800px;
    preferred-height: 600px;

    in-out property <[LogDesc]> logs;
    in-out property <bool> running: false;
    in-out property <bool> stopping: false;
    in-out property <string> status: "Idle";

    in-out property <[LogOptionDesc]> log-options;
    in-out property <int> base-level;

    callback start-emu();
    callback stop-emu();
    callback clear-logs();
    callback base-level-picked(int);
    callback target-level-picked(int /* row */, int /* level */);

    // Called from Rust after new rows are appended to `logs`.
    public function scroll-to-bottom() {
        arm.scroll-to-bottom();
    }

    VerticalBox {
        TabWidget {
            Tab {
                title: "ARM Emulation";
                arm := ArmEmu {
                    logs: root.logs;
                    running: root.running;
                    stopping: root.stopping;
                    status: root.status;
                    start-emu => { root.start-emu(); }
                    stop-emu => { root.stop-emu(); }
                    clear-logs => { root.clear-logs(); }
                }
            }
            Tab {
                title: "PPC Emulation";
                WipView {}
            }
            Tab {
                title: "Debugging";
                WipView {}
            }
            Tab {
                title: "Haxx";
                WipView {}
            }
            Tab {
                title: "Options";
                OptionsPane {
                    log-options: root.log-options;
                    base-level: root.base-level;
                    base-level-picked(lvl) => { root.base-level-picked(lvl); }
                    target-level-picked(row, lvl) => { root.target-level-picked(row, lvl); }
                }
            }
            Tab {
                title: "About";
                AboutSlint { height: 75px; }
            }
        }
    }
}
